base_images:
  cli:
    name: "4.13"
    namespace: ocp
    tag: cli
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.19
images:
- context_dir: .
  dockerfile_path: Dockerfile
  to: 3scale-runner
releases:
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.13"
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: 3scale-amp-interop-aws
  cron: 0 1 * * 1
  steps:
    cluster_profile: aws-cspi-qe
    env:
      AWS_REGION: us-east-2
      BASE_DOMAIN: aws.interop.ccitredhat.com
      DEPL_BUCKET_NAME: 3scale-apimanager-s3-bucket
      DEPL_PROJECT_NAME: threescale
      OPERATORS: |
        [
            {"name": "3scale-operator", "source": "redhat-operators", "channel": "!default", "install_namespace": "threescale", "target_namespaces": "threescale"}
        ]
      SPOT_INSTANCES: "true"
    post:
    - ref: gather-aws-console
    - ref: 3scale-apimanager-uninstall
    - chain: ipi-deprovision
    pre:
    - chain: ipi-conf-aws
    - chain: ipi-install
    - ref: install-operators
    - ref: 3scale-apimanager-install
zz_generated_metadata:
  branch: main
  org: 3scale-qe
  repo: 3scale-deploy
  variant: 3scale-amp-ocp4.13-lp-interop
