base_images:
  cli:
    name: "4.13"
    namespace: ocp
    tag: cli
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.19
images:
- context_dir: .
  dockerfile_path: Dockerfile
  to: openshift-pipelines-runner
releases:
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.13"
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: openshift-pipelines-interop-aws
  cron: 0 6 * * 1
  remote_api: true
  steps:
    cluster_profile: aws-cspi-qe
    env:
      BASE_DOMAIN: cspilp.interop.ccitredhat.com
      OPERATORS: |
        [
            {"name": "openshift-pipelines-operator-rh", "source": "redhat-operators", "channel": "!default", "install_namespace": "openshift-operators"}
        ]
      SPOT_INSTANCES: "true"
    test:
    - ref: install-operators
    - ref: openshift-pipelines-interop-tests
    workflow: ipi-aws
zz_generated_metadata:
  branch: interop-v1.10
  org: cchetna
  repo: release-tests
  variant: openshift-pipelines-ocp4.13-lp-interop
