base_images:
  cli:
    name: "4.14"
    namespace: ocp
    tag: cli
releases:
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.14"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: amq-broker-interop-aws
  cron: 0 6 25 12 *
  steps:
    cluster_profile: aws-cspi-qe
    env:
      BASE_DOMAIN: cspilp.interop.ccitredhat.com
    workflow: ipi-aws
zz_generated_metadata:
  branch: lpt
  org: rh-messaging-qe
  repo: claire
  variant: amq-broker-ocp4.14-lp-interop
