base_images:
  cli:
    name: "4.14"
    namespace: ocp
    tag: cli
releases:
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.14"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: amq-broker-interop-aws
  cron: 0 6 25 12 *
  steps:
    cluster_profile: aws-cspi-qe
    env:
      BASE_DOMAIN: cspilp.interop.ccitredhat.com
      FIREWATCH_CONFIG: |
        [
          {"step": "ipi-*", "failure_type": "all", "classification": "Infrastructure Provisioning - Cluster", "jira_project": "LPTOCPCI"},
          {"step": "gather-*", "failure_type": "pod_failure", "classification": "Other", "jira_project": "LPTOCPCI"},
          {"step": "gather-*", "failure_type": "test_failure", "classification": "NONE", "jira_project": "NONE", "ignore": "true"},
          {"step": "openshift-*", "failure_type": "all", "classification": "Other", "jira_project": "LPTOCPCI"},
          {"step": "amq-broker-install-and-tests", "failure_type": "pod_failure", "classification": "Test Failure", "jira_project": "LPTOCPCI"},
          {"step": "amq-broker-install-and-tests", "failure_type": "test_failure", "classification": "Test Failure", "jira_project": "ENTMQBR"}
        ]
      FIREWATCH_DEFAULT_JIRA_PROJECT: LPTOCPCI
      FIREWATCH_JIRA_SERVER: https://issues.redhat.com
      SLEEP_DURATION: 2h
    test:
    - ref: wait
    workflow: firewatch-ipi-aws
zz_generated_metadata:
  branch: lpt
  org: rh-messaging-qe
  repo: claire
  variant: amq-broker-ocp4.14-lp-interop
