base_images:
  cli:
    name: "4.13"
    namespace: ocp
    tag: cli
releases:
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.13"
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: 3scale-amp-interop-aws
  cron: 0 1 * * 1
  steps:
    cluster_profile: aws-cspi-qe
    env:
      BASE_DOMAIN: aws.interop.ccitredhat.com
      COMPUTE_NODE_REPLICAS: "3"
      COMPUTE_NODE_TYPE: m5.xlarge
      OPERATORS: |
        [
            {"name": "3scale-operator", "source": "redhat-operators", "channel": "threescale-2.13", "install_namespace": "threescale", "target_namespaces": "threescale"}
        ]
      SPOT_INSTANCES: "true"
    test:
    - ref: install-operators
    workflow: ipi-aws
zz_generated_metadata:
  branch: main
  org: 3scale-qe
  repo: 3scale-tests
  variant: 3scale-amp-ocp4.13-lp-interop
