base_images:
  cli:
    name: "4.13"
    namespace: ocp
    tag: cli
releases:
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.13"
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: 3scale-amp-interop-aws
  cron: 0 1 * * 1
  steps:
    cluster_profile: aws-cspi-qe
    env:
      BASE_DOMAIN: aws.interop.ccitredhat.com
      SPOT_INSTANCES: "true"
    workflow: ipi-aws
zz_generated_metadata:
  branch: main
  org: 3scale-qe
  repo: 3scale-tests
  variant: 3scale-amp-ocp4.13-lp-interop
