base_images:
  cli:
    name: "4.16"
    namespace: ocp
    tag: cli
  console-tests:
    name: "4.17"
    namespace: ocp
    tag: console-tests
releases:
  initial:
    integration:
      name: "4.17"
      namespace: ocp
  latest:
    release:
      channel: candidate
      version: "4.17"
resources:
  '*':
    limits:
      memory: 6Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: 417-rc-iib
  cron: 0 6 11 2 *
  steps:
    cluster_profile: aws-managed-cspi-qe
    test:
    - as: odc-tests
      cli: latest
      commands: echo "dummy command"
      from: console-tests
      resources:
        requests:
          cpu: 100m
zz_generated_metadata:
  branch: main
  org: chetna14manku
  repo: serverless-operator
  variant: p2p-4.17-test
