base_images:
  cli:
    name: "4.16"
    namespace: ocp
    tag: cli
  cli-ocm:
    name: cli-ocm
    namespace: ci
    tag: latest
  console-tests:
    name: "4.17"
    namespace: ocp
    tag: console-tests
  ocp_4.17_cli:
    name: "4.17"
    namespace: ocp
    tag: cli
  ocp_ubi-minimal_8:
    name: ubi-minimal
    namespace: ocp
    tag: "8"
  openshift-cli-installer:
    name: openshift-cli-installer
    namespace: ci
    tag: latest
  openshift_eventing-istio-src_knative-v1.14:
    name: eventing-istio-src
    namespace: openshift
    tag: knative-v1.14
  openshift_eventing-kafka-broker-src_knative-v1.14:
    name: eventing-kafka-broker-src
    namespace: openshift
    tag: knative-v1.14
  openshift_knative-eventing-src_knative-v1.14:
    name: knative-eventing-src
    namespace: openshift
    tag: knative-v1.14
  openshift_knative-serving-src_knative-v1.14:
    name: knative-serving-src
    namespace: openshift
    tag: knative-v1.14
  openshift_release_rhel-9-release-golang-1.22-openshift-4.17:
    name: release
    namespace: openshift
    tag: rhel-9-release-golang-1.22-openshift-4.17
  origin_4.17_operator-registry:
    name: "4.17"
    namespace: origin
    tag: operator-registry
  rosa-aws-cli:
    name: rosa-aws-cli
    namespace: ci
    tag: latest
build_root:
  project_image:
    dockerfile_path: openshift/ci-operator/build-image/Dockerfile
images:
- dockerfile_path: knative-operator/Dockerfile
  inputs:
    ocp_ubi-minimal_8:
      as:
      - registry.ci.openshift.org/ocp/ubi-minimal:8
    openshift_release_rhel-9-release-golang-1.22-openshift-4.17:
      as:
      - registry.ci.openshift.org/openshift/release:rhel-9-release-golang-1.22-openshift-4.17
  to: serverless-knative-operator
- dockerfile_path: olm-catalog/serverless-operator/Dockerfile
  to: serverless-bundle
- dockerfile_path: olm-catalog/serverless-operator/index/Dockerfile
  inputs:
    origin_4.17_operator-registry:
      as:
      - registry.ci.openshift.org/origin/4.17:operator-registry
  to: serverless-index
- dockerfile_path: openshift-knative-operator/Dockerfile
  inputs:
    ocp_ubi-minimal_8:
      as:
      - registry.ci.openshift.org/ocp/ubi-minimal:8
    openshift_release_rhel-9-release-golang-1.22-openshift-4.17:
      as:
      - registry.ci.openshift.org/openshift/release:rhel-9-release-golang-1.22-openshift-4.17
  to: serverless-openshift-knative-operator
- dockerfile_path: openshift/ci-operator/source-image/Dockerfile
  from: src
  inputs:
    ocp_4.17_cli:
      as:
      - registry.ci.openshift.org/ocp/4.17:cli
    openshift_eventing-istio-src_knative-v1.14:
      as:
      - registry.ci.openshift.org/openshift/eventing-istio-src:knative-v1.14
    openshift_eventing-kafka-broker-src_knative-v1.14:
      as:
      - registry.ci.openshift.org/openshift/eventing-kafka-broker-src:knative-v1.14
    openshift_knative-eventing-src_knative-v1.14:
      as:
      - registry.ci.openshift.org/openshift/knative-eventing-src:knative-v1.14
    openshift_knative-serving-src_knative-v1.14:
      as:
      - registry.ci.openshift.org/openshift/knative-serving-src:knative-v1.14
  to: serverless-source-image
- dockerfile_path: serving/ingress/Dockerfile
  inputs:
    ocp_ubi-minimal_8:
      as:
      - registry.ci.openshift.org/ocp/ubi-minimal:8
    openshift_release_rhel-9-release-golang-1.22-openshift-4.17:
      as:
      - registry.ci.openshift.org/openshift/release:rhel-9-release-golang-1.22-openshift-4.17
  to: serverless-ingress
- dockerfile_path: serving/metadata-webhook/Dockerfile
  inputs:
    ocp_ubi-minimal_8:
      as:
      - registry.ci.openshift.org/ocp/ubi-minimal:8
    openshift_release_rhel-9-release-golang-1.22-openshift-4.17:
      as:
      - registry.ci.openshift.org/openshift/release:rhel-9-release-golang-1.22-openshift-4.17
  to: serverless-metadata-webhook
releases:
  latest:
    release:
      channel: candidate
      version: "4.17"
resources:
  '*':
    limits:
      memory: 6Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: 417-rc-iib
  cron: 0 6 11 2 *
  steps:
    allow_best_effort_post_steps: true
    cluster_profile: aws-managed-cspi-qe
    env:
      CLUSTER1_CONFIG: platform=rosa;region=us-east-2;version=4.17;channel-group=nightly;compute-machine-type=m5.4xlarge;timeout=2h;replicas=2;fips=true;ocm-env=stage
      SLEEP_DURATION: 4h
    test:
    - as: mesh-e2e-install
      best_effort: true
      cli: latest
      commands: SKIP_MESH_AUTH_POLICY_GENERATION=true make install-for-mesh-e2e
      dependencies:
      - env: SERVERLESS_KNATIVE_OPERATOR
        name: serverless-knative-operator
      - env: SERVERLESS_BUNDLE
        name: serverless-bundle
      - env: SERVERLESS_INDEX
        name: serverless-index
      - env: SERVERLESS_OPENSHIFT_KNATIVE_OPERATOR
        name: serverless-openshift-knative-operator
      - env: SERVERLESS_SOURCE_IMAGE
        name: serverless-source-image
      - env: SERVERLESS_INGRESS
        name: serverless-ingress
      - env: SERVERLESS_METADATA_WEBHOOK
        name: serverless-metadata-webhook
      from: serverless-source-image
      resources:
        requests:
          cpu: 100m
      timeout: 4h0m0s
    - as: odc-tests
      best_effort: true
      cli: latest
      commands: |
        status=0
        ./test-prow-e2e.sh knative || status="$?" || true
        cp -r /go/src/github.com/openshift/console/frontend/gui_test_screenshots/* ${ARTIFACT_DIR} 2>/dev/null || true
        exit $status
      from: console-tests
      resources:
        requests:
          cpu: 100m
      timeout: 2h0m0s
    - ref: wait
    workflow: cluster
  timeout: 6h0m0s
zz_generated_metadata:
  branch: main
  org: chetna14manku
  repo: serverless-operator
  variant: debug
