base_images:
  cli:
    name: "4.14"
    namespace: ocp
    tag: cli
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.19
images:
- context_dir: .
  dockerfile_path: Dockerfile
  to: camel-k-runner
releases:
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.14"
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: camel-k-interop-aws
  cron: 0 6 * * 1
  remote_api: true
  steps:
    cluster_profile: aws-cspi-qe
    env:
      BASE_DOMAIN: cspilp.interop.ccitredhat.com
      OPERATORS: |
        [
            {"name": "red-hat-camel-k", "source": "redhat-operators", "channel": "latest", "install_namespace": "openshift-operators"}
        ]
    test:
    - ref: install-operators
    - ref: camel-k-interop-tests
    workflow: ipi-aws
zz_generated_metadata:
  branch: main
  org: jboss-fuse
  repo: camel-k-test-container
  variant: camel-k-ocp4.14-lp-interop
