base_images:
  cli:
    name: "4.14"
    namespace: ocp
    tag: cli
releases:
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.14"
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: openshift-pipelines-interop-aws
  cron: 0 6 * * 1
  remote_api: true
  steps:
    cluster_profile: aws-cspi-qe
    env:
      BASE_DOMAIN: cspilp.interop.ccitredhat.com
      OPERATORS: |
        [
            {"name": "openshift-pipelines-operator-rh", "source": "redhat-operators", "channel": "!default", "install_namespace": "openshift-operators"}
        ]
      SPOT_INSTANCES: "true"
    test:
    - ref: install-operators
    workflow: ipi-aws
zz_generated_metadata:
  branch: release-v1.10
  org: openshift-pipelines
  repo: release-tests
  variant: openshift-pipelines-ocp4.14-lp-interop
