base_images:
  ocp_4.16_base-rhel9:
    name: "4.16"
    namespace: ocp
    tag: base-rhel9
  ocp_builder_rhel-9-base-nodejs-openshift-4.16:
    name: builder
    namespace: ocp
    tag: rhel-9-base-nodejs-openshift-4.16
  ocp_builder_rhel-9-golang-1.21-openshift-4.16:
    name: builder
    namespace: ocp
    tag: rhel-9-golang-1.21-openshift-4.16
build_root:
  from_repository: true
images:
- dockerfile_path: Dockerfile
  inputs:
    ocp_4.16_base-rhel9:
      as:
      - registry.ci.openshift.org/ocp/4.16:base-rhel9
    ocp_builder_rhel-9-base-nodejs-openshift-4.16:
      as:
      - registry.ci.openshift.org/ocp/builder:rhel-9-base-nodejs-openshift-4.16
    ocp_builder_rhel-9-golang-1.21-openshift-4.16:
      as:
      - registry.ci.openshift.org/ocp/builder:rhel-9-golang-1.21-openshift-4.16
  to: console-release-4.16
promotion:
  to:
  - name: odc-serverless-4.16
    namespace: ocp
releases:
  initial:
    integration:
      name: "4.16"
      namespace: ocp
  latest:
    integration:
      include_built_images: true
      name: "4.16"
      namespace: ocp
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
zz_generated_metadata:
  branch: release-4.16
  org: openshift
  repo: console
  variant: odc-serverless-p2p
